import { ProgressIndicator, Palette, VerticalBox } from "std-widgets.slint";

export component ProcessingPage inherits VerticalBox {
    alignment: center;
    spacing: 20px;
    padding: 20px;

    in property <float> progress: 0.0;

    Text {
        text: "Processing Map Data...";
        font-size: 20px;
        font-weight: 700;
        horizontal-alignment: center;
        color: Palette.foreground;
    }
    
    Text {
        text: "This may take a minute. Please don't close the application.";
        font-size: 14px;
        horizontal-alignment: center;
        color: Palette.foreground;
    }

    ProgressIndicator {
        progress: root.progress;
        width: 100%;
        height: 20px;
    }
}
