import { Button, LineEdit, ScrollView, Palette } from "std-widgets.slint";

export component RegionSelectionPage inherits VerticalLayout {
    alignment: stretch;
    padding: 20px;
    spacing: 15px;

    in property <[string]> available_regions;
    in-out property <string> selected_region: "";

    callback download_requested(string);
    callback search_changed(string);

    Text {
        text: "Select Map Region to Download:";
        font-size: 16px;
        horizontal-alignment: center;
        color: Palette.foreground;
    }

    search-box := LineEdit {
        placeholder-text: "Search for a region or U.S. state (e.g., 'North')...";
        edited => {
            root.search_changed(self.text);
        }
        accepted => {
            if (root.available_regions.length == 1) {
                root.selected_region = root.available_regions[0];
            }
        }
    }

    Rectangle {
        border-color: Palette.border;
        border-width: 1px;
        border-radius: 4px;
        vertical-stretch: 1;
        background: Palette.control-background;

        ScrollView {
            width: 100%;
            height: 100%;
            VerticalLayout {
                alignment: start;
                for region in root.available_regions: TouchArea {
                    height: 35px;
                    clicked => {
                        root.selected_region = region;
                    }
                    Rectangle {
                        background: root.selected_region == region ? Palette.selection-background : (parent.has-hover ? Palette.alternate-background : transparent);
                        Text {
                            text: region;
                            vertical-alignment: center;
                            x: 10px;
                            color: root.selected_region == region ? Palette.selection-foreground : Palette.foreground;
                            font-size: 14px;
                        }
                    }
                }
            }
        }
    }

    HorizontalLayout {
        spacing: 10px;
        alignment: start;
        Text {
            text: "Selected Region:";
            font-size: 14px;
            font-weight: 700;
            vertical-alignment: center;
            color: Palette.foreground;
        }

        Text {
            text: root.selected_region == "" ? "None" : root.selected_region;
            color: root.selected_region == "" ? Palette.foreground : Palette.selection-background;
            font-size: 14px;
            font-weight: 700;
            vertical-alignment: center;
        }
    }

    Button {
        text: "Download Map";
        enabled: root.selected_region != "";
        clicked => {
            root.download_requested(root.selected_region);
        }
    }
}
